# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pycharmworkspace\Intellectual-testing-system\interface\Windows\registration.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationWindow(object):
    def setupUi(self, RegistrationWindow):
        RegistrationWindow.setObjectName("RegistrationWindow")
        RegistrationWindow.resize(640, 400)
        self.centralwidget = QtWidgets.QWidget(RegistrationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.loginLine = QtWidgets.QLineEdit(self.centralwidget)
        self.loginLine.setObjectName("loginLine")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.loginLine)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.passwordLine = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordLine.setObjectName("passwordLine")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passwordLine)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.nameLine = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLine.setObjectName("nameLine")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.nameLine)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.faternityLine = QtWidgets.QLineEdit(self.centralwidget)
        self.faternityLine.setObjectName("faternityLine")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.faternityLine)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.dateOfBirth = QtWidgets.QDateEdit(self.centralwidget)
        self.dateOfBirth.setObjectName("dateOfBirth")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.dateOfBirth)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.registerButton = QtWidgets.QPushButton(self.centralwidget)
        self.registerButton.setObjectName("registerButton")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.registerButton)
        self.group = QtWidgets.QComboBox(self.centralwidget)
        self.group.setObjectName("group")
        self.group.addItem("")
        self.group.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.group)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.question = QtWidgets.QComboBox(self.centralwidget)
        self.question.setObjectName("question")
        self.question.addItem("")
        self.question.addItem("")
        self.question.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.question)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.answerLine = QtWidgets.QLineEdit(self.centralwidget)
        self.answerLine.setObjectName("answerLine")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.answerLine)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setText("")
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.errorLabel)
        self.emailLine = QtWidgets.QLineEdit(self.centralwidget)
        self.emailLine.setObjectName("emailLine")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.emailLine)
        self.phoneLine = QtWidgets.QLineEdit(self.centralwidget)
        self.phoneLine.setObjectName("phoneLine")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.phoneLine)
        self.photoButton = QtWidgets.QPushButton(self.centralwidget)
        self.photoButton.setObjectName("photoButton")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.photoButton)
        RegistrationWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegistrationWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistrationWindow)

    def retranslateUi(self, RegistrationWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistrationWindow.setWindowTitle(_translate("RegistrationWindow", "MainWindow"))
        self.label.setText(_translate("RegistrationWindow", "Регистрация"))
        self.label_3.setText(_translate("RegistrationWindow", "Логин*"))
        self.label_4.setText(_translate("RegistrationWindow", "Пароль*"))
        self.label_5.setText(_translate("RegistrationWindow", "Имя*"))
        self.label_6.setText(_translate("RegistrationWindow", "Фамилия*"))
        self.label_7.setText(_translate("RegistrationWindow", "Отчество"))
        self.label_8.setText(_translate("RegistrationWindow", "Дата рождения*"))
        self.label_9.setText(_translate("RegistrationWindow", "Группа*"))
        self.registerButton.setText(_translate("RegistrationWindow", "PushButton"))
        self.group.setItemText(0, _translate("RegistrationWindow", "18БИ1"))
        self.group.setItemText(1, _translate("RegistrationWindow", "18БИ2"))
        self.label_10.setText(_translate("RegistrationWindow", "Секретный вопрос*"))
        self.question.setItemText(0, _translate("RegistrationWindow", "Вопрос1"))
        self.question.setItemText(1, _translate("RegistrationWindow", "Вопрос2"))
        self.question.setItemText(2, _translate("RegistrationWindow", "Вопрос3"))
        self.label_11.setText(_translate("RegistrationWindow", "Ответ*"))
        self.label_2.setText(_translate("RegistrationWindow", "Эл. почта*"))
        self.label_12.setText(_translate("RegistrationWindow", "Телефон"))
        self.label_13.setText(_translate("RegistrationWindow", "Фото"))
        self.photoButton.setText(_translate("RegistrationWindow", "PushButton"))
